# 任务名称
name: deploy-server-jar

#提交到哪个分支，触发任务
on:
  push:
    branches:
      - master

#任务详情
jobs:

  #job名称
  build:

    #使用哪个runner获取job并执行
    runs-on: self-hosted

    #任务步骤
    steps:
      - name: echo dir
        run: dir=`pwd` && echo $dir