# 任务名称
name: deploy-server-jar

#提交到哪个分支，触发任务
on:
  push:
    branches:
      - master

#任务详情
jobs:

  #job名称
  build:

    #使用哪个runner获取job并执行
    runs-on: self-hosted

    #任务步骤
    steps:
      - name: echo dir
        run: dir=`pwd` && echo $dir
      - name: pull code
        run: git pull origin master
      - name: build project
        run: mvn clean package -Dmaven.test.skip=true
      - name: move to work dir
        run: cd ./target && mv weixin-test-0.0.1-SNAPSHOT.jar /data/wx-test/server
      - name: deploy
        run: supervisorctl restart wx-test